### ISSUE TITLE
DecimalMath: Convergence in Asin() is poor for arguments near 1 (by absolute value)

### ISSUE THREAD

**Issue by FrancescaY** [raminrahimzada/CSharp-Helper-Classes#2]
You implemented a straightforward Taylor series for Asin() which converges poorly with arguments near 1. This makes the solution not really practicable. Would be great to have a more efficient algorithm.

**Comment by raminrahimzada** [comment]
With  the help of some math equalities (shown in source )
 I think that I solved this issue

**Comment by FrancescaY** [comment]
Tested it, works great! Thanks Ramin!
