### ISSUE TITLE
DecimalMath.Power(value, pow) crashes with negative values

### ISSUE THREAD

**Issue by alsinaleandro** [raminrahimzada/CSharp-Helper-Classes#4]
DecimalMath.Power(decimal value, decimal pow) crashes with negative values. Because internally, it performs Log(value), and the Log function does not accept negative values. It even will crash on zero value, because Log(zero) is negative infinity.

**Comment by raminrahimzada** [comment]
@alsinaleandro 
Thanks for the contribution,
Solved this bug with validating the sign of base value
And checked some  special cases such as 
0^0
negative^fraction
etc.

**Comment by alsinaleandro** [comment]
great! many thanks to you
