### ISSUE TITLE
This seems like a redundant check

### ISSUE THREAD

**Issue by seantheyahn** [raminrahimzada/CSharp-Helper-Classes#8]
`pow` could not be zero in this line, therefore `pow == Zero` is always false.

https://github.com/raminrahimzada/CSharp-Helper-Classes/blob/ffbb33c1ee90ce12357c72fa65f2510a09834693/Math/DecimalMath/DecimalMath.cs#L120

**Comment by raminrahimzada** [comment]
Hi @seantheyahn 
It was really a redundant line and now removed it

Thanks for contributing !
