### ISSUE TITLE
Does this code have a license or allow external usage?

### ISSUE THREAD

**Issue by tommyettinger** [raminrahimzada/CSharp-Helper-Classes#9]
I get the impression from the MIT-licensed https://github.com/raminrahimzada/YoutuBot repo you've provided that you prefer the MIT license and also don't want to waste time on legal stuff, so mostly I'm asking: Would you be willing to either license the decimal math code as MIT, or just provide some written permission for me to copy it into an open-source project? I hope you don't mind that I copied most of the decimal math functions, with only minor changes, into my own repo that currently holds mostly those functions: https://github.com/tommyettinger/determon . I would like to publish my determon repo to Nuget, but I think it's best if I get your permission first or you establish some license for this repo. I can credit you however you want; you're almost entirely the sole author of determon at this point, though I'd like to add some more decimal-related math functions and possibly some other kinds of deterministic decimal-based generation code. If you don't want to permit external usage, I'll attempt to look elsewhere for implementations of decimal math in C#, but yours really do look like the best option for me at this point in time.

Thank you for your time, and for writing this handy library.

**Comment by raminrahimzada** [comment]
@tommyettinger  thanks for caring about author rights firstly,
I am not a person wants to claim smth to be mine with law, 
Despite, these codes took me lot more paperwork calculations and hours to debug for finding  better ways  
It was my need and I developed it so you can also use it where you want if you need this
What  I care about is maybe there is uncovered bug inside codes and may broke someone's production
I don't want to get responsibility for these type of cases, If you ever see this case Of course I will try to fix in my repo
Summary : feel free to use and deploy in anywhere)

**Comment by tommyettinger** [comment]
Your work is really helpful, thank you! I haven't found any actual bugs in your code; it's impressively precise. There's one issue with naming, where Math.Atan() is called DecimalMath.ATan() here, and a few tiny cases where some conditionals can be simplified, but nothing that is especially serious. I wouldn't change the naming of a method in DecimalMath because, like you said, we don't want to break production code, but I do change it in my Determon library. Regarding responsibility, that's a major reason why the MIT license has the wording it does: it allows usage but does not allow holding the author (in this case, you) responsible for any problems users encounter in their code (you have "indemnity," as in "it is impossible to con**demn** you"). Without a license any usage has to be approved by the author, who could allow any usage freely, charge a fee to use, charge different fees for different uses, or not allow any use. The problem with that last group of options is that it's legally messy (and unless you mention it with users, there isn't indemnity for you, which is a hassle to ensure), so that's a big reason licenses get used for open source code. MIT also allows using the code in pretty much any type of project, commercial or non-commercial; that's probably why Microsoft chose it for .NET Core.

I'm fairly sure if I include DecimalMath with some changes in Determon, and Determon has an MIT license, then people who use Determon can't blame anyone who wrote code in the library for bugs in their code that result from using the library. That means I couldn't be blamed by users and you couldn't be blamed at all, which I think is best, certainly. If you felt like it, you (only you) could prevent future versions of Determon from using the same license, unless I removed your DecimalMath class and any copied code. I don't think you'd do something like that, like you said.

I'll notify you of any bugs I find, or that users find, when I become aware of them; you can also choose to watch the Determon repo in case someone posts issues there. I think I'm OK to release an alpha pre-release version of Determon now on Nuget, and if anyone has problems with something I will try to fix them before any stable release.
